// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: pet.sql

package db

import (
	"context"
	"database/sql"
)

const createPet = `-- name: CreatePet :one
INSERT INTO pets (
    name, about, user_id, age, gender, pet_type, breed, image_id, medical_condition
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, name, about, user_id, age, gender, pet_type, breed, image_id, medical_condition, created_at, updated_at
`

type CreatePetParams struct {
	Name             string         `json:"name"`
	About            sql.NullString `json:"about"`
	UserID           int64          `json:"user_id"`
	Age              int32          `json:"age"`
	Gender           string         `json:"gender"`
	PetType          string         `json:"pet_type"`
	Breed            sql.NullString `json:"breed"`
	ImageID          sql.NullInt64  `json:"image_id"`
	MedicalCondition sql.NullString `json:"medical_condition"`
}

func (q *Queries) CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error) {
	row := q.db.QueryRowContext(ctx, createPet,
		arg.Name,
		arg.About,
		arg.UserID,
		arg.Age,
		arg.Gender,
		arg.PetType,
		arg.Breed,
		arg.ImageID,
		arg.MedicalCondition,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.About,
		&i.UserID,
		&i.Age,
		&i.Gender,
		&i.PetType,
		&i.Breed,
		&i.ImageID,
		&i.MedicalCondition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePet = `-- name: DeletePet :exec
DELETE FROM pets
WHERE id = $1
`

func (q *Queries) DeletePet(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePet, id)
	return err
}

const getPet = `-- name: GetPet :one
SELECT id, name, about, user_id, age, gender, pet_type, breed, image_id, medical_condition, created_at, updated_at FROM pets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPet(ctx context.Context, id int64) (Pet, error) {
	row := q.db.QueryRowContext(ctx, getPet, id)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.About,
		&i.UserID,
		&i.Age,
		&i.Gender,
		&i.PetType,
		&i.Breed,
		&i.ImageID,
		&i.MedicalCondition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePet = `-- name: UpdatePet :one
UPDATE pets
SET 
    name = $1,
    about = $2,
    age = $3,
    gender = $4,
    pet_type = $5,
    breed = $6,
    image_id = $7,
    medical_condition = $8,
    updated_at = now()

WHERE id = $9
RETURNING id, name, about, user_id, age, gender, pet_type, breed, image_id, medical_condition, created_at, updated_at
`

type UpdatePetParams struct {
	Name             string         `json:"name"`
	About            sql.NullString `json:"about"`
	Age              int32          `json:"age"`
	Gender           string         `json:"gender"`
	PetType          string         `json:"pet_type"`
	Breed            sql.NullString `json:"breed"`
	ImageID          sql.NullInt64  `json:"image_id"`
	MedicalCondition sql.NullString `json:"medical_condition"`
	ID               int64          `json:"id"`
}

func (q *Queries) UpdatePet(ctx context.Context, arg UpdatePetParams) (Pet, error) {
	row := q.db.QueryRowContext(ctx, updatePet,
		arg.Name,
		arg.About,
		arg.Age,
		arg.Gender,
		arg.PetType,
		arg.Breed,
		arg.ImageID,
		arg.MedicalCondition,
		arg.ID,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.About,
		&i.UserID,
		&i.Age,
		&i.Gender,
		&i.PetType,
		&i.Breed,
		&i.ImageID,
		&i.MedicalCondition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
